/*
   DivvyDroid - Application to screencast and remote control Android devices.

   Copyright (C) 2019 - Mladen Milinkovic <maxrd2@smoothware.net>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "input_to_adroid_keys.h"

#include "input/android_keycodes.h"

QMap<Qt::Key, int> qtToAndroidCode = {
	{Qt::Key_Escape, AKEYCODE_ESCAPE},
	{Qt::Key_Backspace, AKEYCODE_DEL},
	{Qt::Key_Space, AKEYCODE_SPACE},
	{Qt::Key_Tab, AKEYCODE_TAB},
	{Qt::Key_Enter, AKEYCODE_ENTER},
	{Qt::Key_Return, AKEYCODE_ENTER},
	{Qt::Key_F1, AKEYCODE_F1},
	{Qt::Key_F2, AKEYCODE_F2},
	{Qt::Key_F3, AKEYCODE_F3},
	{Qt::Key_F4, AKEYCODE_F4},
	{Qt::Key_F5, AKEYCODE_F5},
	{Qt::Key_F6, AKEYCODE_F6},
	{Qt::Key_F7, AKEYCODE_F7},
	{Qt::Key_F8, AKEYCODE_F8},
	{Qt::Key_F9, AKEYCODE_F9},
	{Qt::Key_F10, AKEYCODE_F10},
	{Qt::Key_Home, AKEYCODE_MOVE_HOME},
	{Qt::Key_Up, AKEYCODE_DPAD_UP},
	{Qt::Key_Left, AKEYCODE_DPAD_LEFT},
	{Qt::Key_Right, AKEYCODE_DPAD_RIGHT},
	{Qt::Key_End, AKEYCODE_MOVE_END},
	{Qt::Key_Down, AKEYCODE_DPAD_DOWN},
	{Qt::Key_Insert, AKEYCODE_INSERT},
	{Qt::Key_Delete, AKEYCODE_FORWARD_DEL},
	{Qt::Key_0, AKEYCODE_0},
	{Qt::Key_1, AKEYCODE_1},
	{Qt::Key_2, AKEYCODE_2},
	{Qt::Key_3, AKEYCODE_3},
	{Qt::Key_4, AKEYCODE_4},
	{Qt::Key_5, AKEYCODE_5},
	{Qt::Key_6, AKEYCODE_6},
	{Qt::Key_7, AKEYCODE_7},
	{Qt::Key_8, AKEYCODE_8},
	{Qt::Key_9, AKEYCODE_9},
	{Qt::Key_A, AKEYCODE_A},
	{Qt::Key_B, AKEYCODE_B},
	{Qt::Key_C, AKEYCODE_C},
	{Qt::Key_D, AKEYCODE_D},
	{Qt::Key_E, AKEYCODE_E},
	{Qt::Key_F, AKEYCODE_F},
	{Qt::Key_G, AKEYCODE_G},
	{Qt::Key_H, AKEYCODE_H},
	{Qt::Key_I, AKEYCODE_I},
	{Qt::Key_J, AKEYCODE_J},
	{Qt::Key_K, AKEYCODE_K},
	{Qt::Key_L, AKEYCODE_L},
	{Qt::Key_M, AKEYCODE_M},
	{Qt::Key_N, AKEYCODE_N},
	{Qt::Key_O, AKEYCODE_O},
	{Qt::Key_P, AKEYCODE_P},
	{Qt::Key_Q, AKEYCODE_Q},
	{Qt::Key_R, AKEYCODE_R},
	{Qt::Key_S, AKEYCODE_S},
	{Qt::Key_T, AKEYCODE_T},
	{Qt::Key_U, AKEYCODE_U},
	{Qt::Key_V, AKEYCODE_V},
	{Qt::Key_W, AKEYCODE_W},
	{Qt::Key_X, AKEYCODE_X},
	{Qt::Key_Y, AKEYCODE_Y},
	{Qt::Key_Z, AKEYCODE_Z},
	{Qt::Key_Shift, AKEYCODE_SHIFT_LEFT},
	{Qt::Key_Control, AKEYCODE_CTRL_LEFT},
	{Qt::Key_Meta, AKEYCODE_META_LEFT},
	{Qt::Key_Alt, AKEYCODE_ALT_LEFT},
	{Qt::Key_AltGr, AKEYCODE_ALT_RIGHT},
	{Qt::Key_Plus, AKEYCODE_PLUS},
	{Qt::Key_Minus, AKEYCODE_MINUS},
	{Qt::Key_Asterisk, AKEYCODE_NUMPAD_MULTIPLY},
	{Qt::Key_Slash, AKEYCODE_SLASH},
	{Qt::Key_Backslash, AKEYCODE_BACKSLASH},
};


// NOTE: this mappings might be inaccurate
int keyToAndroidCode[249] = {
	AKEYCODE_UNKNOWN,			// 0: KEY_RESERVED
	AKEYCODE_ESCAPE,			// 1: KEY_ESC
	AKEYCODE_1,					// 2: KEY_1
	AKEYCODE_2,					// 3: KEY_2
	AKEYCODE_3,					// 4: KEY_3
	AKEYCODE_4,					// 5: KEY_4
	AKEYCODE_5,					// 6: KEY_5
	AKEYCODE_6,					// 7: KEY_6
	AKEYCODE_7,					// 8: KEY_7
	AKEYCODE_8,					// 9: KEY_8
	AKEYCODE_9,					// 10: KEY_9
	AKEYCODE_0,					// 11: KEY_0
	AKEYCODE_MINUS,				// 12: KEY_MINUS
	AKEYCODE_EQUALS,			// 13: KEY_EQUAL
	AKEYCODE_DEL,				// 14: KEY_BACKSPACE
	AKEYCODE_TAB,				// 15: KEY_TAB
	AKEYCODE_Q,					// 16: KEY_Q
	AKEYCODE_W,					// 17: KEY_W
	AKEYCODE_E,					// 18: KEY_E
	AKEYCODE_R,					// 19: KEY_R
	AKEYCODE_T,					// 20: KEY_T
	AKEYCODE_Y,					// 21: KEY_Y
	AKEYCODE_U,					// 22: KEY_U
	AKEYCODE_I,					// 23: KEY_I
	AKEYCODE_O,					// 24: KEY_O
	AKEYCODE_P,					// 25: KEY_P
	AKEYCODE_UNKNOWN,			// 26: KEY_LEFTBRACE '{'
	AKEYCODE_UNKNOWN,			// 27: KEY_RIGHTBRACE '}'
	AKEYCODE_ENTER,				// 28: KEY_ENTER
	AKEYCODE_CTRL_LEFT,			// 29: KEY_LEFTCTRL
	AKEYCODE_A,					// 30: KEY_A
	AKEYCODE_S,					// 31: KEY_S
	AKEYCODE_D,					// 32: KEY_D
	AKEYCODE_F,					// 33: KEY_F
	AKEYCODE_G,					// 34: KEY_G
	AKEYCODE_H,					// 35: KEY_H
	AKEYCODE_J,					// 36: KEY_J
	AKEYCODE_K,					// 37: KEY_K
	AKEYCODE_L,					// 38: KEY_L
	AKEYCODE_SEMICOLON,			// 39: KEY_SEMICOLON
	AKEYCODE_APOSTROPHE,		// 40: KEY_APOSTROPHE
	AKEYCODE_GRAVE,				// 41: KEY_GRAVE
	AKEYCODE_SHIFT_LEFT,		// 42: KEY_LEFTSHIFT
	AKEYCODE_BACKSLASH,			// 43: KEY_BACKSLASH
	AKEYCODE_Z,					// 44: KEY_Z
	AKEYCODE_X,					// 45: KEY_X
	AKEYCODE_C,					// 46: KEY_C
	AKEYCODE_V,					// 47: KEY_V
	AKEYCODE_B,					// 48: KEY_B
	AKEYCODE_N,					// 49: KEY_N
	AKEYCODE_M,					// 50: KEY_M
	AKEYCODE_COMMA,				// 51: KEY_COMMA
	AKEYCODE_PERIOD,			// 52: KEY_DOT
	AKEYCODE_SLASH,				// 53: KEY_SLASH
	AKEYCODE_SHIFT_RIGHT,		// 54: KEY_RIGHTSHIFT
	AKEYCODE_NUMPAD_MULTIPLY,	// 55: KEY_KPASTERISK
	AKEYCODE_ALT_LEFT,			// 56: KEY_LEFTALT
	AKEYCODE_SPACE,				// 57: KEY_SPACE
	AKEYCODE_CAPS_LOCK,			// 58: KEY_CAPSLOCK
	AKEYCODE_F1,				// 59: KEY_F1
	AKEYCODE_F2,				// 60: KEY_F2
	AKEYCODE_F3,				// 61: KEY_F3
	AKEYCODE_F4,				// 62: KEY_F4
	AKEYCODE_F5,				// 63: KEY_F5
	AKEYCODE_F6,				// 64: KEY_F6
	AKEYCODE_F7,				// 65: KEY_F7
	AKEYCODE_F8,				// 66: KEY_F8
	AKEYCODE_F9,				// 67: KEY_F9
	AKEYCODE_F10,				// 68: KEY_F10
	AKEYCODE_NUM_LOCK,			// 69: KEY_NUMLOCK
	AKEYCODE_SCROLL_LOCK,		// 70: KEY_SCROLLLOCK
	AKEYCODE_NUMPAD_7,			// 71: KEY_KP7
	AKEYCODE_NUMPAD_8,			// 72: KEY_KP8
	AKEYCODE_NUMPAD_9,			// 73: KEY_KP9
	AKEYCODE_NUMPAD_SUBTRACT,	// 74: KEY_KPMINUS
	AKEYCODE_NUMPAD_4,			// 75: KEY_KP4
	AKEYCODE_NUMPAD_5,			// 76: KEY_KP5
	AKEYCODE_NUMPAD_6,			// 77: KEY_KP6
	AKEYCODE_NUMPAD_ADD,		// 78: KEY_KPPLUS
	AKEYCODE_NUMPAD_1,			// 79: KEY_KP1
	AKEYCODE_NUMPAD_2,			// 80: KEY_KP2
	AKEYCODE_NUMPAD_3,			// 81: KEY_KP3
	AKEYCODE_NUMPAD_0,			// 82: KEY_KP0
	AKEYCODE_NUMPAD_DOT,		// 83: KEY_KPDOT
	AKEYCODE_UNKNOWN,			// 84: missing
	AKEYCODE_ZENKAKU_HANKAKU,	// 85: KEY_ZENKAKUHANKAKU
	AKEYCODE_UNKNOWN,			// 86: KEY_102ND
	AKEYCODE_F11,				// 87: KEY_F11
	AKEYCODE_F12,				// 88: KEY_F12
	AKEYCODE_RO,				// 89: KEY_RO
	AKEYCODE_UNKNOWN,			// 90: KEY_KATAKANA
	AKEYCODE_UNKNOWN,			// 91: KEY_HIRAGANA
	AKEYCODE_HENKAN,			// 92: KEY_HENKAN
	AKEYCODE_KATAKANA_HIRAGANA,	// 93: KEY_KATAKANAHIRAGANA
	AKEYCODE_MUHENKAN,			// 94: KEY_MUHENKAN
	AKEYCODE_NUMPAD_COMMA,		// 95: KEY_KPJPCOMMA
	AKEYCODE_NUMPAD_ENTER,		// 96: KEY_KPENTER
	AKEYCODE_CTRL_RIGHT,		// 97: KEY_RIGHTCTRL
	AKEYCODE_NUMPAD_DIVIDE,		// 98: KEY_KPSLASH
	AKEYCODE_SYSRQ,				// 99: KEY_SYSRQ
	AKEYCODE_ALT_RIGHT,			// 100: KEY_RIGHTALT
	AKEYCODE_ENTER,				// 101: KEY_LINEFEED
	AKEYCODE_MOVE_HOME,			// 102: KEY_HOME
	AKEYCODE_DPAD_UP,			// 103: KEY_UP
	AKEYCODE_UNKNOWN,			// 104: KEY_PAGEUP
	AKEYCODE_DPAD_LEFT,			// 105: KEY_LEFT
	AKEYCODE_DPAD_RIGHT,		// 106: KEY_RIGHT
	AKEYCODE_MOVE_END,			// 107: KEY_END
	AKEYCODE_DPAD_DOWN,			// 108: KEY_DOWN
	AKEYCODE_UNKNOWN,			// 109: KEY_PAGEDOWN
	AKEYCODE_INSERT,			// 110: KEY_INSERT
	AKEYCODE_FORWARD_DEL,		// 111: KEY_DELETE
	AKEYCODE_UNKNOWN,			// 112: KEY_MACRO
	AKEYCODE_MUTE,				// 113: KEY_MUTE
	AKEYCODE_VOLUME_DOWN,		// 114: KEY_VOLUMEDOWN
	AKEYCODE_VOLUME_UP,			// 115: KEY_VOLUMEUP
	AKEYCODE_POWER,				// 116: KEY_POWER SC System Power Down
	AKEYCODE_NUMPAD_EQUALS,		// 117: KEY_KPEQUAL
	AKEYCODE_UNKNOWN,			// 118: KEY_KPPLUSMINUS
	AKEYCODE_UNKNOWN,			// 119: KEY_PAUSE
	AKEYCODE_UNKNOWN,			// 120: KEY_SCALE AL Compiz Scale (Expose)
	AKEYCODE_NUMPAD_COMMA,		// 121: KEY_KPCOMMA
	AKEYCODE_UNKNOWN,			// 122: KEY_HANGEUL
	AKEYCODE_UNKNOWN,			// 123: KEY_HANJA
	AKEYCODE_YEN,				// 124: KEY_YEN
	AKEYCODE_META_LEFT,			// 125: KEY_LEFTMETA
	AKEYCODE_META_RIGHT,		// 126: KEY_RIGHTMETA
	AKEYCODE_UNKNOWN,			// 127: KEY_COMPOSE
	AKEYCODE_UNKNOWN,			// 128: KEY_STOP AC Stop
	AKEYCODE_UNKNOWN,			// 129: KEY_AGAIN
	AKEYCODE_UNKNOWN,			// 130: KEY_PROPS AC Properties
	AKEYCODE_UNKNOWN,			// 131: KEY_UNDO AC Undo
	AKEYCODE_UNKNOWN,			// 132: KEY_FRONT
	AKEYCODE_COPY,				// 133: KEY_COPY AC Copy
	AKEYCODE_UNKNOWN,			// 134: KEY_OPEN AC Open
	AKEYCODE_PASTE,				// 135: KEY_PASTE AC Paste
	AKEYCODE_UNKNOWN,			// 136: KEY_FIND AC Search
	AKEYCODE_CUT,				// 137: KEY_CUT AC Cut
	AKEYCODE_HELP,				// 138: KEY_HELP AL Integrated Help Center
	AKEYCODE_MENU,				// 139: KEY_MENU Menu (show menu)
	AKEYCODE_UNKNOWN,			// 140: KEY_CALC AL Calculator
	AKEYCODE_UNKNOWN,			// 141: KEY_SETUP
	AKEYCODE_SLEEP,				// 142: KEY_SLEEP SC System Sleep
	AKEYCODE_WAKEUP,			// 143: KEY_WAKEUP System Wake Up
	AKEYCODE_UNKNOWN,			// 144: KEY_FILE AL Local Machine Browser
	AKEYCODE_UNKNOWN,			// 145: KEY_SENDFILE
	AKEYCODE_UNKNOWN,			// 146: KEY_DELETEFILE
	AKEYCODE_UNKNOWN,			// 147: KEY_XFER
	AKEYCODE_UNKNOWN,			// 148: KEY_PROG1
	AKEYCODE_UNKNOWN,			// 149: KEY_PROG2
	AKEYCODE_UNKNOWN,			// 150: KEY_WWW AL Internet Browser
	AKEYCODE_UNKNOWN,			// 151: KEY_MSDOS
	AKEYCODE_UNKNOWN,			// 152: KEY_SCREENLOCK AL Terminal Lock/Screensaver
	AKEYCODE_UNKNOWN,			// 153: KEY_ROTATE_DISPLAY Display orientation for e.g. tablets
	AKEYCODE_UNKNOWN,			// 154: KEY_CYCLEWINDOWS
	AKEYCODE_UNKNOWN,			// 155: KEY_MAIL
	AKEYCODE_UNKNOWN,			// 156: KEY_BOOKMARKS AC Bookmarks
	AKEYCODE_UNKNOWN,			// 157: KEY_COMPUTER
	AKEYCODE_BACK,				// 158: KEY_BACK AC Back
	AKEYCODE_FORWARD,			// 159: KEY_FORWARD AC Forward
	AKEYCODE_MEDIA_CLOSE,		// 160: KEY_CLOSECD
	AKEYCODE_MEDIA_EJECT,		// 161: KEY_EJECTCD
	AKEYCODE_UNKNOWN,			// 162: KEY_EJECTCLOSECD
	AKEYCODE_MEDIA_NEXT,		// 163: KEY_NEXTSONG
	AKEYCODE_MEDIA_PLAY_PAUSE,	// 164: KEY_PLAYPAUSE
	AKEYCODE_MEDIA_PREVIOUS,	// 165: KEY_PREVIOUSSONG
	AKEYCODE_MEDIA_STOP,		// 166: KEY_STOPCD
	AKEYCODE_MEDIA_RECORD,		// 167: KEY_RECORD
	AKEYCODE_MEDIA_REWIND,		// 168: KEY_REWIND
	AKEYCODE_UNKNOWN,			// 169: KEY_PHONE Media Select Telephone
	AKEYCODE_UNKNOWN,			// 170: KEY_ISO
	AKEYCODE_UNKNOWN,			// 171: KEY_CONFIG AL Consumer Control Configuration
	AKEYCODE_HOME,				// 172: KEY_HOMEPAGE AC Home
	AKEYCODE_REFRESH,			// 173: KEY_REFRESH AC Refresh
	AKEYCODE_UNKNOWN,			// 174: KEY_EXIT AC Exit
	AKEYCODE_UNKNOWN,			// 175: KEY_MOVE
	AKEYCODE_UNKNOWN,			// 176: KEY_EDIT
	AKEYCODE_UNKNOWN,			// 177: KEY_SCROLLUP
	AKEYCODE_UNKNOWN,			// 178: KEY_SCROLLDOWN
	AKEYCODE_NUMPAD_LEFT_PAREN,	// 179: KEY_KPLEFTPAREN
	AKEYCODE_NUMPAD_RIGHT_PAREN,// 180: KEY_KPRIGHTPAREN
	AKEYCODE_UNKNOWN,			// 181: KEY_NEW AC New
	AKEYCODE_UNKNOWN,			// 182: KEY_REDO AC Redo/Repeat
	AKEYCODE_UNKNOWN,			// 183: KEY_F13
	AKEYCODE_UNKNOWN,			// 184: KEY_F14
	AKEYCODE_UNKNOWN,			// 185: KEY_F15
	AKEYCODE_UNKNOWN,			// 186: KEY_F16
	AKEYCODE_UNKNOWN,			// 187: KEY_F17
	AKEYCODE_UNKNOWN,			// 188: KEY_F18
	AKEYCODE_UNKNOWN,			// 189: KEY_F19
	AKEYCODE_UNKNOWN,			// 190: KEY_F20
	AKEYCODE_UNKNOWN,			// 191: KEY_F21
	AKEYCODE_UNKNOWN,			// 192: KEY_F22
	AKEYCODE_UNKNOWN,			// 193: KEY_F23
	AKEYCODE_UNKNOWN,			// 194: KEY_F24
	AKEYCODE_UNKNOWN,			// 195: missing
	AKEYCODE_UNKNOWN,			// 196: missing
	AKEYCODE_UNKNOWN,			// 197: missing
	AKEYCODE_UNKNOWN,			// 198: missing
	AKEYCODE_UNKNOWN,			// 199: missing
	AKEYCODE_MEDIA_PLAY,		// 200: KEY_PLAYCD
	AKEYCODE_MEDIA_PAUSE,		// 201: KEY_PAUSECD
	AKEYCODE_UNKNOWN,			// 202: KEY_PROG3
	AKEYCODE_UNKNOWN,			// 203: KEY_PROG4
	AKEYCODE_UNKNOWN,			// 204: KEY_DASHBOARD AL Dashboard
	AKEYCODE_UNKNOWN,			// 205: KEY_SUSPEND
	AKEYCODE_MEDIA_CLOSE,		// 206: KEY_CLOSE AC Close
	AKEYCODE_MEDIA_PLAY,		// 207: KEY_PLAY
	AKEYCODE_MEDIA_FAST_FORWARD,// 208: KEY_FASTFORWARD
	AKEYCODE_UNKNOWN,			// 209: KEY_BASSBOOST
	AKEYCODE_UNKNOWN,			// 210: KEY_PRINT AC Print
	AKEYCODE_UNKNOWN,			// 211: KEY_HP
	AKEYCODE_CAMERA,			// 212: KEY_CAMERA
	AKEYCODE_UNKNOWN,			// 213: KEY_SOUND
	AKEYCODE_UNKNOWN,			// 214: KEY_QUESTION
	AKEYCODE_UNKNOWN,			// 215: KEY_EMAIL
	AKEYCODE_UNKNOWN,			// 216: KEY_CHAT
	AKEYCODE_SEARCH,		    // 217: KEY_SEARCH
	AKEYCODE_UNKNOWN,			// 218: KEY_CONNECT
	AKEYCODE_UNKNOWN,			// 219: KEY_FINANCE AL Checkbook/Finance
	AKEYCODE_UNKNOWN,			// 220: KEY_SPORT
	AKEYCODE_UNKNOWN,			// 221: KEY_SHOP
	AKEYCODE_UNKNOWN,			// 222: KEY_ALTERASE
	AKEYCODE_UNKNOWN,			// 223: KEY_CANCEL AC Cancel
	AKEYCODE_BRIGHTNESS_DOWN,	// 224: KEY_BRIGHTNESSDOWN
	AKEYCODE_BRIGHTNESS_UP,		// 225: KEY_BRIGHTNESSUP
	AKEYCODE_UNKNOWN,			// 226: KEY_MEDIA
	AKEYCODE_UNKNOWN,			// 227: KEY_SWITCHVIDEOMODE Cycle between available video outputs (Monitor/LCD/TV-out/etc)
	AKEYCODE_UNKNOWN,			// 228: KEY_KBDILLUMTOGGLE
	AKEYCODE_UNKNOWN,			// 229: KEY_KBDILLUMDOWN
	AKEYCODE_UNKNOWN,			// 230: KEY_KBDILLUMUP
	AKEYCODE_UNKNOWN,			// 231: KEY_SEND AC Send
	AKEYCODE_UNKNOWN,			// 232: KEY_REPLY AC Reply
	AKEYCODE_UNKNOWN,			// 233: KEY_FORWARDMAIL AC Forward Msg
	AKEYCODE_UNKNOWN,			// 234: KEY_SAVE AC Save
	AKEYCODE_UNKNOWN,			// 235: KEY_DOCUMENTS
	AKEYCODE_UNKNOWN,			// 236: KEY_BATTERY
	AKEYCODE_UNKNOWN,			// 237: KEY_BLUETOOTH
	AKEYCODE_UNKNOWN,			// 238: KEY_WLAN
	AKEYCODE_UNKNOWN,			// 239: KEY_UWB
	AKEYCODE_UNKNOWN,			// 240: KEY_UNKNOWN
	AKEYCODE_UNKNOWN,			// 241: KEY_VIDEO_NEXT drive next video source
	AKEYCODE_UNKNOWN,			// 242: KEY_VIDEO_PREV drive previous video source
	AKEYCODE_UNKNOWN,			// 243: KEY_BRIGHTNESS_CYCLE brightness up, after max is min
	AKEYCODE_UNKNOWN,			// 244: KEY_BRIGHTNESS_AUTO Set Auto Brightness: manual brightness control is off, rely on ambient
	AKEYCODE_UNKNOWN,			// 245: KEY_DISPLAY_OFF display device to off state
	AKEYCODE_UNKNOWN,			// 246: KEY_WWAN Wireless WAN (LTE, UMTS, GSM, etc.)
	AKEYCODE_UNKNOWN,			// 247: KEY_RFKILL Key that controls all radios
	AKEYCODE_UNKNOWN			// 248: KEY_MICMUTE Mute / unmute the microphone
};

